/**
 * Dynamic Expo config — inlined for EAS CLI compatibility.
 *
 * EAS CLI cannot require() TypeScript files (gas.config.ts).
 * This file inlines the config data needed at build time.
 * gas.config.ts remains the runtime source of truth (Metro handles TS).
 *
 * Auto-generated by DevAgent — do not edit manually.
 */

const config = {
  app: {
    name: "GolfTrip Organizer",
    slug: "golftrip-organizer",
    scheme: "golftrip-organizer",
    version: "1.0.0",
    owner: "goodspeed_app_studio"
  },
  design: {
    colors: {
      primary: "#1A3A2A"
    }
  },
  features: {
    auth: {
      apple: true,
      biometric: {
        enabled: true
      }
    },
    pushNotifications: {
      enabled: true
    },
    compliance: {
      attDialog: false
    },
    onboarding: {
      enabled: true
    },
    inAppPurchases: {
      enabled: true
    }
  }
};

const slug = config.app.slug;
const bundleSlug = slug.replace(/-/g, '_');

// Build plugins array based on enabled features
const plugins = [
  'expo-router',
  'expo-secure-store',
  [
    'expo-build-properties',
    {
android: {
        targetSdkVersion: 35,
        compileSdkVersion: 36,
      },
    },
  ],
];

if (config.features.auth.biometric.enabled) {
  plugins.push('expo-local-authentication');
}

if (config.features.auth.apple) {
  plugins.push('expo-apple-authentication');
}

if (config.features.pushNotifications.enabled) {
  plugins.push([
    'expo-notifications',
    {
      icon: './assets/images/notification-icon.png',
      color: config.design.colors.primary,
    },
  ]);
}

if (config.features.compliance.attDialog) {
  plugins.push([
    'expo-tracking-transparency',
    {
      userTrackingPermission:
        'This identifier will be used to deliver personalized ads to you.',
    },
  ]);
}

if (process.env.EXPO_PUBLIC_SENTRY_DSN) {
  plugins.push([
    '@sentry/react-native/expo',
    {
      organization: process.env.SENTRY_ORG ?? 'goodspeed',
      project: process.env.SENTRY_PROJECT ?? slug,
    },
  ]);
}

const EAS_PROJECT_ID = 'd662cc12-d08f-499b-8086-095fe6ebb829';

module.exports = ({ config: expoConfig }) => ({
  ...expoConfig,
  name: config.app.name,
  slug: slug,
  version: config.app.version,
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: config.app.scheme || slug,
  userInterfaceStyle: 'automatic',
  owner: config.app.owner,
  splash: {
    image: './assets/images/splash.png',
    resizeMode: 'contain',
    backgroundColor: config.design.colors.primary,
  },
  ios: {
    supportsTablet: true,
    bundleIdentifier: `com.goodspeed.${slug}`,
    usesAppleSignIn: config.features.auth.apple,
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/images/adaptive-icon.png',
      backgroundColor: config.design.colors.primary,
    },
    package: `com.goodspeed.${bundleSlug}`,
    blockedPermissions: [
      'android.permission.ACTIVITY_RECOGNITION',
    ],
  },
web: {
    bundler: 'metro',
    output: 'single',
    // favicon intentionally omitted — gas-template does not ship one, and
    // pointing at a non-existent path makes expo export fail. The web
    // preview will use a default favicon; a real one can be added later.
  },
  plugins,
  experiments: {
    typedRoutes: true,
  },
  updates: {
    url: `https://u.expo.dev/${EAS_PROJECT_ID}`,
  },
  runtimeVersion: {
    policy: 'appVersion',
  },
  extra: {
    eas: {
      projectId: EAS_PROJECT_ID,
    },
  },
});
