// AUTO-GENERATED by packages/gas-config-schema/scripts/emit-types.mts.
// DO NOT EDIT BY HAND.
// To regenerate: pnpm --filter @goodspeed/gas-config-schema emit-types
//
// This file is the single source of truth for the Gas* interfaces consumed by:
//   - gas-template/gas.config.ts (runtime declarations)
//   - packages/development/src/dev-agent.ts (codegen-time references)
//   - any other goodspeed code that reads .gas.config.ts values
//
// The emitter walks every Z<Name> zod schema export in
// packages/gas-config-schema/src/gas-config.ts and emits one
// `export interface <Name>` (or `export type <Name>` for non-object schemas)
// matching the schema's structural type.

export interface CrashFreePerPlatform {
  ios: number;
  android: number;
}


// ─── Admin / Monitoring ───────────────────────────────────────────────────────

export interface GasAdminConfig {
  enabled: boolean;
  defaultRoleCheck: string;
}

export interface GasAdsFeatures {
  enabled: boolean;
  provider: "admob";
}

export interface GasAnalyticsFeatures {
  enabled: boolean;
  provider: "posthog";
  crashReporting: boolean;
  sessionRecording: boolean;
  featureFlags: boolean;
}

export interface GasAnonymousAuthFeatures {
  enabled: boolean;
  tables: Array<string>;
}


// ─── App / Design ─────────────────────────────────────────────────────────────

export interface GasAppConfig {
  name: string;
  slug: string;
  description: string;
  scheme: string;
  version: string;
  owner: string;
  minRuntimeVersion: string;
  updateBranch: "preview" | "staging" | "production";
  appStoreUrl?: string;
}


// ─── Features ─────────────────────────────────────────────────────────────────

export interface GasAuthFeatures {
  email: true;
  google: boolean;
  apple: boolean;
  twitter: boolean;
  linkedin?: boolean;
  microsoft?: boolean;
  mfa?: boolean;
  biometric: {
  enabled: boolean;
  timeoutMinutes: number;
};
  magicLink: boolean;
  guestMode: boolean;
}

export interface GasBackendConfig {
  supabase: {
  url: string;
  anonKey: string;
};
  revenuecat: {
  iosKey: string;
  androidKey: string;
};
  posthog: {
  apiKey: string;
  host: string;
};
  telemetry: {
  ingestSecret: string;
};
  stripe?: {
  publishableKey: string;
};
}

export interface GasColorPalette {
  primary: string;
  primaryDark: string;
  secondary: string;
  accent: string;
  background: string;
  backgroundDark: string;
  surface: string;
  surfaceDark: string;
  text: string;
  textDark: string;
  textSecondary: string;
  textSecondaryDark: string;
  border: string;
  borderDark: string;
  success: string;
  warning: string;
  error: string;
}

export interface GasComplianceConfig {
  accountDeletionGracePeriod: {
  days: number;
};
  allowImmediateDeletion: boolean;
  exportTables: Array<string>;
  consentBannerRequired: "always" | "eu_only" | "never";
}

export interface GasComplianceFeatures {
  attDialog: boolean;
  gdprConsent: boolean;
  ccpaNotice: boolean;
  ageGate: boolean;
  dataExport: boolean;
}


// ─── Top-level ─────────────────────────────────────────────────────────────────

export interface GasConfig {
  app: GasAppConfig;
  backend: GasBackendConfig;
  design: GasDesignSystem;
  features: GasFeatures;
  navigation: GasNavigation;
  privacy: GasPrivacyConfig;
  compliance: GasComplianceConfig;
  observability: GasObservabilityConfig;
  costBudgets: GasCostBudgetsConfig;
  releaseChannels: GasReleaseChannelsConfig;
  performance: GasPerformanceConfig;
  media: GasMediaConfig;
  search: GasSearchConfig;
  realtime: GasRealtimeConfig;
  integrations: GasIntegrationsConfig;
  e2e: GasE2eConfig;
  llm: GasLlmConfig;
  ui: GasUiConfig;
  multiTenancy: GasMultiTenancyConfig;
  growth: GasGrowthConfig;
  admin: GasAdminConfig;
  monitoring: GasMonitoringConfig;
}

export interface GasCostBudgetSeed {
  scope: string;
  period: "hour" | "day" | "month";
  costLimit: number;
  enforcement: "throttle" | "block" | "alert_only";
  throttleCapacity?: number;
  throttleRefillPerSecond?: number;
}

export interface GasCostBudgetsConfig {
  defaults: Record<string, GasCostBudgetSeed>;
}

export interface GasCreditPack {
  id: string;
  productId: string;
  name: string;
  credits: number;
  price: string;
  bonusCredits?: number;
  popular?: boolean;
}

export interface GasCreditsConfig {
  enabled: boolean;
  currencyName: string;
  currencyNamePlural: string;
  iconName: string;
  packs: Array<GasCreditPack>;
  initialBalance?: number;
}

export interface GasDarkModeFeatures {
  enabled: boolean;
  default: "system" | "dark" | "light";
}

export interface GasDesignSystem {
  mood: "minimal" | "playful" | "professional" | "bold" | "warm" | "energetic" | "calm" | "dark";
  colors: GasColorPalette;
  typography: GasTypography;
  layout: GasLayout;
}

export interface GasE2eConfig {
  framework: "maestro";
  cloudWorkspaceId: string;
}

export interface GasFeatures {
  auth: GasAuthFeatures;
  pushNotifications: GasPushNotificationFeatures;
  notifications?: GasNotificationsConfig;
  inAppPurchases: GasInAppPurchaseFeatures;
  analytics: GasAnalyticsFeatures;
  telemetry?: GasTelemetryFeatures;
  darkMode: GasDarkModeFeatures;
  offlineSync: GasOfflineSyncFeatures;
  gamification: GasGamificationFeatures;
  onboarding: GasOnboardingFeatures;
  helpSystem: boolean;
  search: GasSearchFeatures;
  socialSharing: GasSocialSharingFeatures;
  i18n: GasI18nFeatures;
  media: GasMediaFeatures;
  compliance: GasComplianceFeatures;
  ads: GasAdsFeatures;
  backgroundFetch: boolean;
  csvExport: boolean;
  showBuiltWithBadge: boolean;
  anonymousAuth?: GasAnonymousAuthFeatures;
}

export interface GasGamificationFeatures {
  enabled: boolean;
  elements: Array<string>;
}

export interface GasGrowthConfig {
  experimentsEnabled: boolean;
  defaultBackgroundSyncInterval: number;
  referralCodeLength: number;
}

export interface GasI18nFeatures {
  enabled: boolean;
  locales: Array<string>;
  defaultLocale: string;
}

export interface GasInAppPurchaseFeatures {
  enabled: boolean;
  tiers: Array<GasSubscriptionTier>;
  oneTimePurchases?: Array<GasOneTimePurchase>;
  credits?: GasCreditsConfig;
  marketplace?: GasMarketplaceConfig;
}

export interface GasIntegrationsConfig {
  oauthProviders: Array<OAuthProviderConfig>;
}

export interface GasLayout {
  borderRadius: "none" | "sm" | "md" | "lg" | "xl" | "2xl" | "full";
  spacing: "compact" | "comfortable" | "spacious";
  cardStyle: "flat" | "elevated" | "outlined" | "filled";
  buttonStyle: "rounded" | "pill" | "square";
  navigationStyle: "standard" | "floating" | "minimal" | "icon-only";
}

export interface GasLlmConfig {
  provider: "openai" | "anthropic";
  defaultChatModel: string;
  defaultEmbedModel: string;
  defaultTranscribeModel: string;
  costScope: string;
  budgetPeriod: "hour" | "day" | "month";
  defaultMaxTokens?: number;
}

export interface GasMarketplaceConfig {
  enabled: boolean;
  platformFeePercent: number;
  sellerPayoutMethod: "stripe_connect";
  listingCategories: Array<string>;
  requiresApproval: boolean;
  escrowEnabled: boolean;
}

export interface GasMediaConfig {
  provider: "supabase" | "r2" | "cloudinary";
  maxUploadBytes: number;
  allowedContentTypes: Array<string>;
  defaultBucket: string;
  maxImageEdge: number;
  signedUrlTtlSeconds: number;
}

export interface GasMediaFeatures {
  imagePicker: boolean;
  camera: boolean;
  audioPlayback: boolean;
  videoPlayback: boolean;
  fileUpload: boolean;
}

export interface GasMonitoringConfig {
  crashFreeThresholds: {
  production: number | CrashFreePerPlatform;
  staging: number | CrashFreePerPlatform;
  preview: number | CrashFreePerPlatform;
};
  crashFreeWindow: "24h" | "7d";
}

export interface GasMultiTenancyConfig {
  enabled: boolean;
  defaultRole: "owner" | "admin" | "member";
}

export interface GasNavigation {
  tabs: Array<GasTabConfig>;
  hiddenScreens: Array<string>;
  modals: Array<string>;
}


// ─── Notifications ────────────────────────────────────────────────────────────

export interface GasNotificationCategoryConfig {
  enabled: boolean;
  defaultOn: boolean;
}

export interface GasNotificationsConfig {
  enabled: boolean;
  categories: {
  transactional: GasNotificationCategoryConfig;
  product: GasNotificationCategoryConfig;
  marketing: GasNotificationCategoryConfig;
};
  receiptPolling?: GasReceiptPollingConfig;
}

export interface GasObservabilityConfig {
  sentryDsn: string;
  tracesSampleRate: number;
  enableSessionReplay: boolean;
}

export interface GasOfflineSyncFeatures {
  enabled: boolean;
  cachedEntities: Array<string>;
  syncStrategy: "on_reconnect" | "periodic";
  encrypted?: boolean;
}

export interface GasOnboardingFeatures {
  enabled: boolean;
  steps: Array<string>;
}

export interface GasOneTimePurchase {
  id: string;
  productId: string;
  name: string;
  price: string;
  description: string;
  type: "lifetime" | "feature_pack" | "content";
  entitlement?: string;
}

export interface GasPerformanceConfig {
  maxBundleSizeMB: number;
  coldStartTargetMs: number;
}

export interface GasPrivacyConfig {
  dataCategories: Array<GasPrivacyDataCategory>;
  trackingDomains: Array<string>;
  attUsageDescription: string;
  attTriggerEvent: "first_launch" | "after_signup" | "manual";
}

export interface GasPrivacyDataCategory {
  type: string;
  linked: boolean;
  tracking: boolean;
  purposes: Array<string>;
}

export interface GasPushNotificationFeatures {
  enabled: boolean;
  permissionTiming: "after_aha_moment" | "onboarding" | "explicit_opt_in";
  channels: Array<string>;
}

export interface GasRealtimeConfig {
  presenceTimeoutMs: number;
  autoReconnect: boolean;
  defaultRetries: number;
}

export interface GasReceiptPollingConfig {
  enabled: boolean;
  intervalMinutes: number;
  expireAfterMinutes: number;
}

export interface GasReleaseChannelsConfig {
  current: string;
  storeUrl: {
  ios: string;
  android: string;
};
}

export interface GasSearchConfig {
  defaultLanguage: string;
  defaultLimit: number;
  maxLimit: number;
}

export interface GasSearchFeatures {
  enabled: boolean;
  entities: Array<string>;
  implementation: "client-side" | "supabase-fts";
}

export interface GasSocialSharingFeatures {
  enabled: boolean;
  content: Array<string>;
  platforms: Array<string>;
}

export interface GasSubscriptionTier {
  name: string;
  productId: string;
  price: string;
  features: Array<string>;
  trialDays?: number;
}


// ─── Navigation / Backend ────────────────────────────────────────────────────

export interface GasTabConfig {
  id: string;
  label: string;
  icon: string;
  file: string;
}

export interface GasTelemetryFeatures {
  enabled: boolean;
  ingestUrl: string;
  flushIntervalMs: number;
  maxQueueSize: number;
  debugOverlay?: boolean;
}

export interface GasTypography {
  displayFont: string;
  bodyFont: string;
  headingWeight: "700" | "600" | "500";
  monoFont: string;
}

export interface GasUiConfig {
  breakpoints: {
  tablet: number;
  desktop: number;
};
  honorDynamicType: boolean;
  honorReducedMotion: boolean;
}

export interface OAuthProviderConfig {
  provider: string;
  scopes?: Array<string>;
  refreshUrl?: string;
  refreshThresholdMinutes?: number;
}

