/**
 * GAS Template — Master Configuration (CommonJS mirror of gas.config.ts).
 *
 * Node-evaluated build tools (tailwind.config.js, eas-cli) require() this file
 * because they cannot load the TypeScript gas.config.ts. It carries the FULL
 * config so it is safe even if Metro resolves it at runtime.
 *
 * Auto-generated by DevAgent — kept in lockstep with gas.config.ts.
 */

const gasConfig = {
  app: {
    name: "GolfTrip Organizer",
    slug: "golftrip-organizer",
    description: "Plan golf trips with your group. Manage tee times, itineraries, shared costs, and live scores together in one trip workspace.",
    scheme: "golftrip-organizer",
    version: "1.0.0",
    minRuntimeVersion: "1.0.0",
    appStoreUrl: "",
    owner: "osritmos",
  },

  design: {
    mood: "warm",
    colors: {
      text: "#1C1C1E",
      error: "#9B2226",
      accent: "#C9A84C",
      border: "#DDD8CC",
      primary: "#1A3A2A",
      success: "#2D6A4F",
      surface: "#FDFAF4",
      warning: "#B07D2A",
      textDark: "#EDE8DE",
      secondary: "#2C4A3E",
      background: "#F5F0E8",
      borderDark: "#2E3D34",
      primaryDark: "#2C5A40",
      surfaceDark: "#1C2B22",
      textSecondary: "#5C5C4A",
      backgroundDark: "#121A16",
      textSecondaryDark: "#9EA89A",
    },
    typography: {
      bodyFont: "Manrope",
      monoFont: "Courier New",
      displayFont: "Outfit",
      headingWeight: "700",
    },
    layout: {
      spacing: "comfortable",
      cardStyle: "flat",
      buttonStyle: "pill",
      borderRadius: "xl",
      navigationStyle: "standard",
    },
  },

  features: {
    auth: {
      email: true,
      google: true,
      apple: true,
      twitter: false,
      github: false,
      facebook: true,
      discord: false,
      linkedin: false,
      microsoft: false,
      spotify: false,
      slack: false,
      twitch: false,
      notion: false,
      figma: false,
      biometric: {
        enabled: true,
        timeoutMinutes: 5,
      },
      magicLink: false,
      guestMode: false,
      mfa: false,
    },
    pushNotifications: {
      enabled: true,
      permissionTiming: "after_aha_moment",
      channels: [
        "New chat message in your trip",
        "Organizer announcement posted",
        "New member joined your trip",
        "Expense added. Your share is updated.",
        "Scores entered. Leaderboard updated.",
        "Trip starts tomorrow. Check your itinerary.",
        "Round finished? Log your scores now.",
        "Your trip is complete. Generate your Recap Card.",
      ],
    },
    inAppPurchases: {
      enabled: true,
      tiers: [
        {
          name: "Free",
          productId: "golftrip_free",
          price: "$0",
          features: [
            "Unlimited trip creation and editing",
            "Full group itinerary management",
            "Tee time manual entry and email import",
            "Expense logging with golf-specific categories",
            "Automatic cost split calculation (unequal splits by participation)",
            "Settlement summary with manual 'Mark Settled' tracking",
            "Group chat with day/course threading",
            "Organizer announcements",
            "Round scorecard entry (total scores)",
            "Trip leaderboard",
            "Guest access via invite link (no account required)",
            "RSVP tracking",
            "Up to 20 members per trip",
            "Past trips archive",
          ],
        },
        {
          name: "Recap Unlock",
          productId: "golftrip_recap_onetime",
          price: "$2.99",
          features: [
            "Post-trip shareable Recap Card (Instagram Stories / iMessage optimized)",
            "Downloadable trip summary image",
            "Trip stats: winner, best round, group average, total cost per person",
            "Unlocked permanently for that trip",
          ],
        },
        {
          name: "Pro",
          productId: "golftrip_pro_annual",
          price: "$14.99/year",
          features: [
            "All Recap Cards included for every trip (unlimited)",
            "In-app payment settlement tracking with Venmo/PayPal deep-link integration",
            "Hole-by-hole scorecard entry",
            "Game format library (Skins, Nassau, Stableford, Wolf) with auto-calculated side bets",
            "Up to 50 members per trip",
            "Year-over-year performance comparison across all trips",
            "Priority email support",
          ],
          trialDays: 7,
        },
      ],
      oneTimePurchases: [],
      credits: {
        enabled: false,
        currencyName: "credit",
        currencyNamePlural: "credits",
        iconName: "Coins",
        packs: [],
      },
      marketplace: {
        enabled: false,
        platformFeePercent: 0,
        sellerPayoutMethod: "stripe_connect",
        listingCategories: [],
        requiresApproval: true,
        escrowEnabled: false,
      },
    },
    analytics: {
      enabled: true,
      provider: "posthog",
      crashReporting: false,
      sessionRecording: false,
      featureFlags: false,
    },
    darkMode: {
      enabled: true,
      default: "system",
    },
    offlineSync: {
      enabled: true,
      cachedEntities: ["trips", "teeTimes", "expenses", "members", "messages", "leaderboard"],
      syncStrategy: "on_reconnect",
      encrypted: false,
    },
    gamification: {
      enabled: true,
      elements: [
        "Trip leaderboard with live rank positions and animated re-sorting",
        "Winner crown badge (gold) on leaderboard rank #1 position",
        "Round achievement badges: Best Round of the Trip, Most Improved, Closest to Pin (if side bets enabled)",
        "Milestone toasts: 'First expense logged!', 'Full group joined!', 'All rounds complete!'",
        "Year-over-year improvement comparison on Profile ('Your group shot 3.2 strokes better this year')",
        "Trip streak counter on Profile (number of consecutive years with a group trip)",
      ],
    },
    onboarding: {
      enabled: true,
      steps: ["welcome", "step-2", "step-3", "step-4", "step-5", "step-6", "step-7"],
    },
    helpSystem: true,
    search: {
      enabled: true,
      entities: ["trips", "courses", "members", "expenses"],
      implementation: "supabase-fts",
    },
    socialSharing: {
      enabled: true,
      content: [
        "Trip invite link (shareable via SMS, email, iMessage, WhatsApp)",
        "Post-trip Recap Card (styled image optimized for Instagram Stories and iMessage)",
        "Leaderboard screenshot (auto-generated sharable card with winner name and scores)",
        "Individual round scorecard",
      ],
      platforms: ["iMessage", "WhatsApp", "Instagram Stories", "Email", "System Share Sheet"],
    },
    i18n: {
      enabled: false,
      locales: ["en-US"],
      defaultLocale: "en-US",
    },
    media: {
      imagePicker: false,
      camera: false,
      audioPlayback: false,
      videoPlayback: false,
      fileUpload: false,
    },
    compliance: {
      attDialog: false,
      gdprConsent: false,
      ccpaNotice: false,
      ageGate: false,
      dataExport: true,
    },
    ads: {
      enabled: false,
      provider: "admob",
    },
    notifications: {
      enabled: true,
      categories: {
        transactional: {
          enabled: true,
          defaultOn: true,
        },
        product: {
          enabled: true,
          defaultOn: true,
        },
        marketing: {
          enabled: true,
          defaultOn: false,
        },
      },
      receiptPolling: {
        enabled: true,
        intervalMinutes: 5,
        expireAfterMinutes: 30,
      },
    },
    telemetry: {
      enabled: true,
      flushIntervalMs: 30000,
      maxQueueSize: 200,
      debugOverlay: false,
      ingestUrl: "https://goodspeed.app/api/telemetry/ingest",
    },
    anonymousAuth: {
      enabled: false,
      tables: [],
    },
    backgroundFetch: true,
    csvExport: false,
    showBuiltWithBadge: false,
  },

navigation: {
    tabs: [
      {
        id: "dashboard",
        label: "My Trips",
        icon: "Home",
        file: "dashboard",
      },
      {
        id: "profile",
        label: "Profile & Trip History",
        icon: "User",
        file: "profile",
      },
      {
        id: "settings",
        label: "Settings",
        icon: "Settings",
        file: "settings",
      },
    ],
    hiddenScreens: ["trip"],
    modals: ["paywall"],
  },

  releaseChannels: {
    current: "production",
    storeUrl: {
      ios: "",
      android: "",
    },
  },

  compliance: {
    accountDeletionGracePeriod: {
      days: 30,
    },
    allowImmediateDeletion: true,
    exportTables: [
      "profiles",
      "push_tokens",
      "notifications",
      "user_bookmarks",
      "feedback",
      "consent_log",
    ],
    consentBannerRequired: "eu_only",
  },

  ui: {
    breakpoints: {
      tablet: 600,
      desktop: 1024,
    },
    honorDynamicType: true,
    honorReducedMotion: true,
  },

  multiTenancy: {
    enabled: false,
    defaultRole: "member",
  },

  integrations: {
    oauthProviders: [],
  },

  growth: {
    experimentsEnabled: true,
    defaultBackgroundSyncInterval: 60000,
    referralCodeLength: 8,
  },

  media: {
    provider: "supabase",
    maxUploadBytes: 10485760,
    allowedContentTypes: ["image/jpeg", "image/png", "image/webp"],
    defaultBucket: "uploads",
    maxImageEdge: 2048,
    signedUrlTtlSeconds: 3600,
  },

  search: {
    defaultLanguage: "en",
    defaultLimit: 20,
    maxLimit: 100,
  },

  realtime: {
    presenceTimeoutMs: 30000,
    autoReconnect: true,
    defaultRetries: 3,
  },

  llm: {
    provider: "anthropic",
    defaultChatModel: "claude-opus-4-1",
    defaultEmbedModel: "claude-3-5-sonnet-20241022",
    defaultTranscribeModel: "whisper-1",
    costScope: "monthly",
    budgetPeriod: "month",
  },

  backend: {
    supabase: {
      url: process.env.EXPO_PUBLIC_SUPABASE_URL ?? '',
      anonKey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? '',
    },
    revenuecat: {
      iosKey: process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_IOS ?? '',
      androidKey: process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID ?? '',
    },
    posthog: {
      apiKey: process.env.EXPO_PUBLIC_POSTHOG_API_KEY ?? '',
      host: process.env.EXPO_PUBLIC_POSTHOG_HOST ?? 'https://us.i.posthog.com',
    },
    telemetry: {
      // EXPO_PUBLIC_TELEMETRY_INGEST_SECRET — ingest identity HMAC key. Public-bundle
      // value, not an auth secret. TelemetryProvider reads .ingestSecret at module
      // init; the field MUST be present (empty string is OK) or the React tree
      // crashes on first mount. See gas-template GasBackendConfig.telemetry.
      ingestSecret: process.env.EXPO_PUBLIC_TELEMETRY_INGEST_SECRET ?? '',
    },
    stripe: {
      // Same always-emit pattern as telemetry: safe-off empty string at codegen,
      // runtime decides whether to init Stripe based on marketplace.enabled.
      publishableKey: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? '',
    },
  },
};

module.exports = { gasConfig };
module.exports.default = gasConfig;
