// Auto-generated by `npm run gen-types` from the linked Supabase project schema.
// Do not edit manually; run gen-types after every migration change.
// This placeholder exists so DevAgent-generated apps can import the typed
// Database alias before they've run codegen once.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
