import { Redirect } from 'expo-router';

// Auto-generated by DevAgent's route gate: this path was navigated to but had
// no screen of its own. It maps to an existing route, so redirect there rather
// than 404.
export default function RouteRedirect() {
  return <Redirect href="/login" />;
}
